MoviNext/MoviNext.UI.Web/Models/ErrorViewModel.cs
namespace MoviNext.UI.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MoviNext/MoviNext.UI.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MoviNext.UI.Web.Models;
using System.Diagnostics;

namespace MoviNext.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MoviNext/MoviNext.UI.Web/Controllers/UmrichterController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MoviNext.Model;
using MoviNext.Model.Contracts;

namespace MoviNext.UI.Web.Controllers
{
    public class UmrichterController : Controller
    {
        IRepository repo;

        public UmrichterController(IRepository repo)
        {
            this.repo = repo;
        }

        // GET: UmrichterController
        public ActionResult Index()
        {
            return View(repo.Query<Umrichter>());
        }

        // GET: UmrichterController/Details/5
        public ActionResult Details(int id)
        {
            return View(repo.GetById<Umrichter>(id));
        }

        // GET: UmrichterController/Create
        public ActionResult Create()
        {
            return View(new Umrichter() { Frequenz = 100, Leistung = 4, LeistungsEinheit = LeistungsEinheit.MW });
        }

        // POST: UmrichterController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Umrichter um)
        {
            try
            {
                um.Steuerung = new Steuerung();
                repo.Add(um);
                repo.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UmrichterController/Edit/5
        public ActionResult Edit(int id)
        {
            return View(repo.GetById<Umrichter>(id));

        }

        // POST: UmrichterController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Umrichter umrichter)
        {
            try
            {
                repo.Update(umrichter);
                repo.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: UmrichterController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(repo.GetById<Umrichter>(id));

        }

        // POST: UmrichterController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Umrichter umrichter)
        {
            try
            {
                //var toKill = repo.GetById<Umrichter>(id);
                repo.Delete(umrichter);
                repo.SaveChanges();


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MoviNext/MoviNext.UI.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MoviNext/MoviNext.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoviNext.UI.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MoviNext.UI.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MoviNext.UI.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Umrichter" asp-action="Index">Umrichter</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MoviNext.UI.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MoviNext/MoviNext.UI.Web/Views/Umrichter/Create.cshtml
@model MoviNext.Model.Umrichter

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Umrichter</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Spannung" class="control-label"></label>
                <input asp-for="Spannung" class="form-control" />
                <span asp-validation-for="Spannung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpannungsEinheit" class="control-label"></label>
                <input asp-for="SpannungsEinheit" class="form-control" />
                <span asp-validation-for="SpannungsEinheit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Leistung" class="control-label"></label>
                <input asp-for="Leistung" class="form-control" />
                <span asp-validation-for="Leistung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeistungsEinheit" class="control-label"></label>
                <input asp-for="LeistungsEinheit" class="form-control" />
                <span asp-validation-for="LeistungsEinheit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Frequenz" class="control-label"></label>
                <input asp-for="Frequenz" class="form-control" />
                <span asp-validation-for="Frequenz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FrequenzEinheit" class="control-label"></label>
                <input asp-for="FrequenzEinheit" class="form-control" />
                <span asp-validation-for="FrequenzEinheit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UmrichterParameter" class="control-label"></label>
                <input asp-for="UmrichterParameter" class="form-control" />
                <span asp-validation-for="UmrichterParameter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Version" class="control-label"></label>
                <input asp-for="Version" class="form-control" />
                <span asp-validation-for="Version" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NetzAdr" class="control-label"></label>
                <input asp-for="NetzAdr" class="form-control" />
                <span asp-validation-for="NetzAdr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BasisParameter" class="control-label"></label>
                <input asp-for="BasisParameter" class="form-control" />
                <span asp-validation-for="BasisParameter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modified" class="control-label"></label>
                <input asp-for="Modified" class="form-control" />
                <span asp-validation-for="Modified" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoviNext/MoviNext.UI.Web/Views/Umrichter/Delete.cshtml
@model MoviNext.Model.Umrichter

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Umrichter</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Spannung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Spannung)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpannungsEinheit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpannungsEinheit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Leistung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Leistung)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeistungsEinheit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeistungsEinheit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Frequenz)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Frequenz)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FrequenzEinheit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FrequenzEinheit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UmrichterParameter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UmrichterParameter)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Version)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Version)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NetzAdr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NetzAdr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BasisParameter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BasisParameter)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MoviNext/MoviNext.UI.Web/Views/Umrichter/Details.cshtml
@model MoviNext.Model.Umrichter

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Umrichter</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Spannung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Spannung)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpannungsEinheit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpannungsEinheit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Leistung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Leistung)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeistungsEinheit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeistungsEinheit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Frequenz)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Frequenz)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FrequenzEinheit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FrequenzEinheit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UmrichterParameter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UmrichterParameter)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Version)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Version)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NetzAdr)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NetzAdr)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BasisParameter)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BasisParameter)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MoviNext/MoviNext.UI.Web/Views/Umrichter/Edit.cshtml
@model MoviNext.Model.Umrichter

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Umrichter</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Spannung" class="control-label"></label>
                <input asp-for="Spannung" class="form-control" />
                <span asp-validation-for="Spannung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpannungsEinheit" class="control-label"></label>
                <input asp-for="SpannungsEinheit" class="form-control" />
                <span asp-validation-for="SpannungsEinheit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Leistung" class="control-label"></label>
                <input asp-for="Leistung" class="form-control" />
                <span asp-validation-for="Leistung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeistungsEinheit" class="control-label"></label>
                <input asp-for="LeistungsEinheit" class="form-control" />
                <span asp-validation-for="LeistungsEinheit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Frequenz" class="control-label"></label>
                <input asp-for="Frequenz" class="form-control" />
                <span asp-validation-for="Frequenz" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FrequenzEinheit" class="control-label"></label>
                <input asp-for="FrequenzEinheit" class="form-control" />
                <span asp-validation-for="FrequenzEinheit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UmrichterParameter" class="control-label"></label>
                <input asp-for="UmrichterParameter" class="form-control" />
                <span asp-validation-for="UmrichterParameter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Version" class="control-label"></label>
                <input asp-for="Version" class="form-control" />
                <span asp-validation-for="Version" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NetzAdr" class="control-label"></label>
                <input asp-for="NetzAdr" class="form-control" />
                <span asp-validation-for="NetzAdr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BasisParameter" class="control-label"></label>
                <input asp-for="BasisParameter" class="form-control" />
                <span asp-validation-for="BasisParameter" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Created" class="control-label"></label>
                <input asp-for="Created" class="form-control" />
                <span asp-validation-for="Created" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modified" class="control-label"></label>
                <input asp-for="Modified" class="form-control" />
                <span asp-validation-for="Modified" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoviNext/MoviNext.UI.Web/Views/Umrichter/Index.cshtml
@model IEnumerable<MoviNext.Model.Umrichter>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Spannung)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Leistung)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Frequenz)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UmrichterParameter)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Version)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NetzAdr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BasisParameter)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Spannung) @Html.DisplayFor(modelItem => item.SpannungsEinheit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Leistung) @Html.DisplayFor(modelItem => item.LeistungsEinheit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Frequenz) @Html.DisplayFor(modelItem => item.FrequenzEinheit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UmrichterParameter)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Version)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NetzAdr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BasisParameter)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id=item.Id  }) |
                    @Html.ActionLink("Details", "Details", new{ id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new {  id=item.Id })
                </td>
            </tr>
        }
    </tbody>
</table>